### ISSUE TITLE
gzip compression

### ISSUE THREAD

**Issue by mithrandi** [hawkowl/rproxy#1]
Currently requests from rproxy to the origin will allow the origin response to be compressed, where supported. However, requests from the client to rproxy will never receive a compressed response.

**Comment by mithrandi** [comment]
(This probably needs gzip support in the `twisted.web` *server*)

**Comment by hawkowl** [comment]
t.web supports it (gzipsomethingresource)

**Comment by hawkowl** [comment]
I fixed this a week or so ago. Uncovered a twisted bug, too (see https://github.com/twisted/twisted/pull/747)

**Comment by exarkun** [comment]
This seems to break configurations where the backend actually supports gzip encoding..  I just added rproxy to a deployment and the result is that gzipped *content* is delivered to the client.  That is, the encoding of the rproxy response body is double gzip.
